# permissions for end users to edit folders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: folder-editor-role
rules:
- apiGroups:
  - syncthing.buc.sh
  resources:
  - folders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncthing.buc.sh
  resources:
  - folders/status
  verbs:
  - get
