# permissions for end users to edit instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-editor-role
rules:
- apiGroups:
  - syncthing.bus.sh
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncthing.bus.sh
  resources:
  - instances/status
  verbs:
  - get
