
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: default
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncthing.buc.sh
  resources:
  - devices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncthing.buc.sh
  resources:
  - devices/finalizers
  verbs:
  - update
- apiGroups:
  - syncthing.buc.sh
  resources:
  - devices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - syncthing.buc.sh
  resources:
  - folders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncthing.buc.sh
  resources:
  - folders/finalizers
  verbs:
  - update
- apiGroups:
  - syncthing.buc.sh
  resources:
  - folders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - syncthing.buc.sh
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncthing.buc.sh
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - syncthing.buc.sh
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
