apiVersion: syncthing.buc.sh/v1
kind: Instance
metadata:
  name: full-example-instance
spec:
  # operator specific
  enable_instance: true
  enable_config: true
  enable_nodeport: false
  # API Info to manage an existing syncthing (enable_instance=false)
  #url: https://syncthing.my.domain.com:8384/
  #apikey: my-secret-api-key

  # syncthing deployment
  image: docker.io/syncthing/syncthing
  tag: latest
  data_volume:
    name: data-root
    persistentVolumeClaim:
      claimName: syncthing-data
  config_volume:
    name: config-root
    emptyDir: {}
  additional_data: []
  sync_port: 32000
  tls_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA4tNbZbNfjr7jHH2UTCymZn4DPmzqOZSpgimH90FDU4q6kVOn
    8OM++dmtYuSPPul8Iggfe7snQBauGtn1FnIJvpNE131cdNprDGd0L5KbIVKuSccS
    efksVKqIC3MDAvhTvPOhexaygMylhIIkt1esrb3ErAAx66V8DVezghry3pArBjRK
    XibCW3srH6CI3M6gqZBdlN+SO4gW+2mXQ4HOPRYLKxOAQ2BeANs7n2OeCJQTVQcX
    LiQVUlLnUeXBC3KvE+fGeE2az82jFI1/Uy+y88UC9w9dWkGf2E550Gypb+NFmFxA
    6j3477hUO9atkghT6rx8d1M984hIdrp7uL3A+wIDAQABAoIBAE3z61ZBVhbdvXme
    Iugm9C0HI6BBmCGf2L2V/ldYQ4YjiEjHolDkGFGPoMn62Mv7PCEJ/5/rSur4oG8z
    9sn2+ShYvnD8cVjrc5y4tTJgRRYnryRF2TC4FKcoUEb3CNLtewHWDOobe89OBZhL
    jcjAxeST8lJWYtGkdsSzHksZbdxUtAL71wpVNqVAnkvgUB1rib9BtLkIrR6NKNe0
    eu8p8NP4b1UUue3XcjcraoOOvirfhpMWCnUOXjMCrE6+A0Hn+4pRSQlg4cX9M+lK
    fwhTVaGpxChLZn5xYi4lW9EZvEHNMsiuYmajf6mg0tlutFAtRgmIIIs5adOCWTHA
    bSi+ogECgYEA8QEsOrh8Lt2olr6CfptY2nZSg49mo9RRqufe/8QaIOL7izOWQEom
    byffVFvI/foTL/7ED4YeGaCNoBUX49gn6Y8Lt73kKDHm+TPnhfcoiJd3Jn7SekWM
    W6lJ3LrmDqvGb9BMFslJ/po7wV3FQRrz07d6T0lgI2qa0aepNG+qW/sCgYEA8PBV
    3LmK95ObxvEYz812AtF2+mr6oPaDkjkDDe/ltIlQx/z9ZFDpdb7bfZ2tiqiWK/ib
    6yBNU15g6VZCvgYex4nrZdeczF2Otp/vqD3Bd/rnK4VHpE6wMKC69hk/ZDmiMATQ
    N7YFd4rG6hDSsl5OeiTvbhOGFxpplf8YBQTQHwECgYEA2KNkPbieMIahyDeiF+rO
    uToJPCeIbRYq/0UFKMX/crZ2xQ9vLYU5/UtLLop/JwZHfyo01XuKzSCMjmzHl9Ez
    N3iVYOp6EEOjSzmEEeE1d2sn+NuhmbWw0KhhM+BxcpiofNQxwX3ZXNsJge0npjlz
    Gkpg0Kq1l8B5QKLEr9T8v0cCgYEA78BX0GIZNK7/bgFvjSiIa9l/qURWzWFAH3r3
    3SCA1Rtm9Pp8MxyIk5At3VvP2pBTjsG+dUQZbgIWMVqS44A3lJtbUGYzMvFOF9Ai
    rKl3ISrcaeQgHBHpJRprsIQDHnpzN5EymJ1Z51CDC1teLfvF36ltT33CCq9PreC/
    SA84AgECgYEAgbfRBLAAXPmf7xjqzqL/9i+Dk7RpGLpAcynQnZPnngpmmYvEq758
    Ea4MQ20/6vXeljwceAeo/lXlEUh16XDtrlCfnJMmrx6wxNU4zrIcss/Ghm4w5QOU
    KmDuHkWQ6o+9FdMOcohrUVJsmUgKQNsXp9AKgvSRuO//Pv4fPT1YmCM=
    -----END RSA PRIVATE KEY-----
  tls_crt: |
    -----BEGIN CERTIFICATE-----
    MIIDPTCCAiUCFFxXBBQtMm8zGSxniUXbGP4O77VkMA0GCSqGSIb3DQEBCwUAMFox
    CzAJBgNVBAYTAkFUMQ8wDQYDVQQHDAZWaWVubmExEjAQBgNVBAoMCXN5bmN0aGlu
    ZzESMBAGA1UECwwJc3luY3RoaW5nMRIwEAYDVQQDDAlzeW5jdGhpbmcwIBcNMjEw
    NzE5MTQzODAzWhgPMjEyMTA3MTkxNDM4MDNaMFoxCzAJBgNVBAYTAkFUMQ8wDQYD
    VQQHDAZWaWVubmExEjAQBgNVBAoMCXN5bmN0aGluZzESMBAGA1UECwwJc3luY3Ro
    aW5nMRIwEAYDVQQDDAlzeW5jdGhpbmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQDi01tls1+OvuMcfZRMLKZmfgM+bOo5lKmCKYf3QUNTirqRU6fw4z75
    2a1i5I8+6XwiCB97uydAFq4a2fUWcgm+k0TXfVx02msMZ3QvkpshUq5JxxJ5+SxU
    qogLcwMC+FO886F7FrKAzKWEgiS3V6ytvcSsADHrpXwNV7OCGvLekCsGNEpeJsJb
    eysfoIjczqCpkF2U35I7iBb7aZdDgc49FgsrE4BDYF4A2zufY54IlBNVBxcuJBVS
    UudR5cELcq8T58Z4TZrPzaMUjX9TL7LzxQL3D11aQZ/YTnnQbKlv40WYXEDqPfjv
    uFQ71q2SCFPqvHx3Uz3ziEh2unu4vcD7AgMBAAEwDQYJKoZIhvcNAQELBQADggEB
    ADb9VEGQ1zq24QXjnokD5YkncsR/RvfHMJjmGhgCtG93B6oSN7QY0gXzRoA62bKJ
    +BuWRH+XavDAVw24w56E5uvKX8RhuYZUQJS+qGcPJ3L/VxpjD+kGIMLhFD87O3PY
    mLSVmwM93PUWMDtFvUSW6hSlxZtJpttOvGjOnmKC/8lR0cwrzcPiiaSHgG2o49zd
    3ydeZyBoNGFqXSgA4q/LIzLbH2RZ+2T57xkaA4PFeJLgwQy1GEeDmg6F+2siyUjx
    C+6DbKKnudNvd78C0ei9IJpN+jr2ytDNwfwLfgqvdODNXTwizsYsyQvmxABy9GT4
    ieztJ2Z7hWwkk42GoYs0Dhs=
    -----END CERTIFICATE-----

  # syncthing config
  allow_usage_report: false
  insecure_web: false
  admin_user: syncthing
  apikey: my-secret-api-key
  # https_crt: ""
  # https_key: ""
  